name: kitty contributor

on:
  schedule:
    - cron: "0 */5 * * *"

  

jobs:
  create_commit:
    runs-on: ubuntu-latest 
    steps:
      - name: Create random file
        run: |
          git init
          git remote add origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
          git config --global user.email "sonalirajput1088@gmail.com"
          git config --global user.name "Sonali-Rajput"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          ls -a
          echo $RANDOM >> random.txt
          ls -a
          git add -A
          git commit -m"kitty updated your github >.<"
          git push
